### ISSUE TITLE
Cannot import the module 

### ISSUE THREAD

**Issue by rht6226** [openshift-telco/go-netconf-client#2]
github.com/openshift-telco/go-netconf-client/netconf: github.com/openshift-telco/go-netconf-client@v0.1.0: parsing go.mod:
        module declares its path as: github.com/openshift-telco/go-netconf
                but was required as: github.com/openshift-telco/go-netconf-client

**Comment by adetalhouet** [comment]
Hi

Please make sure to use the right version. The only released version is `v0.0.1`

Here is an example of a project using this client: https://github.com/openshift-telco/netconf-operator/blob/main/go.mod#L9 and it is working fine.

Let me know if you have further questions.

**Comment by rht6226** [comment]
Thanks. It worked.
