### ISSUE TITLE
Module declaration issue

### ISSUE THREAD

**Issue by timstpierre-tc** [openshift-telco/go-netconf-client#3]
It looks like there may be an inconsistency in the way the module is declared?

go: finding module for package github.com/openshift-telco/go-netconf-client/netconf/message
go: finding module for package github.com/openshift-telco/go-netconf-client/netconf
go: downloading github.com/openshift-telco/go-netconf-client v0.1.0
go: found github.com/openshift-telco/go-netconf-client/netconf in github.com/openshift-telco/go-netconf-client v0.1.0
go: found github.com/openshift-telco/go-netconf-client/netconf/message in github.com/openshift-telco/go-netconf-client v0.1.0
go: github.com/tucowsinc/calixnetconf imports
	github.com/openshift-telco/go-netconf-client/netconf: github.com/openshift-telco/go-netconf-client@v0.1.0: parsing go.mod:
	module declares its path as: github.com/openshift-telco/go-netconf
	        but was required as: github.com/openshift-telco/go-netconf-client

I can't seem to build it.

**Comment by adetalhouet** [comment]
Please use release `v1.0.5`; i had some issues when first releasing. I released a fresh new version that should work fine and without confusion.

```
$ go get github.com/openshift-telco/go-netconf-client@v1.0.5
go: downloading github.com/openshift-telco/go-netconf-client v1.0.5
go: added github.com/openshift-telco/go-netconf-client v1.0.5
```
